name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -backend-config="bucket=carloslucaswebpage-test-20223"

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: dev
        run: terraform init -reconfigure
      
      - name: Terraform Plan
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: dev
        run: terraform plan

      - name: Terraform Apply
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_bucket_name: ${{ vars.TF_VAR_BUCKET_NAME }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: dev
        run: terraform apply -auto-approve

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment: prd

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: prd
        run: terraform init -reconfigure

      - name: Terraform Plan
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_bucket_name: ${{ vars.TF_VAR_BUCKET_NAME }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: prd
        run: terraform plan

      - name: Terraform Apply
        env:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_bucket_name: ${{ vars.TF_VAR_BUCKET_NAME }}
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_environment: prd
        run: terraform apply -auto-approve
